/**
 * PWA manifest · enables Add-to-Home-Screen on iOS/Android + standalone mode.
 *
 * Generated by Next.js at /manifest.webmanifest at build time. Auto-linked
 * from <head> via Next's file-based metadata convention · no extra config
 * needed in layout.tsx.
 *
 * Icons are the existing /public/icon-{192,512}.png + maskable variant.
 * Theme colors match the brand · cream cream + Base Blue.
 */

import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "CUVETSMO Web3",
    short_name: "CUVET Web3",
    description:
      "Web3 playground สำหรับนิสิตสัตวแพทย์ จุฬาฯ · 4 pillars · gasless mint · educational testnet",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#fffbf4",   // matches --color-bg (cream)
    theme_color: "#0000ff",         // Base Blue · brand mark
    lang: "th-TH",
    categories: ["education", "productivity", "social"],
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/apple-touch-icon.png",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
    shortcuts: [
      {
        name: "Wallet 101",
        short_name: "Wallet",
        description: "เริ่มต้น Web3 ใน 5 นาที",
        url: "/learn/wallet-101",
      },
      {
        name: "Quests",
        short_name: "Quests",
        description: "10 hands-on quests",
        url: "/learn/quests",
      },
      {
        name: "Vet SBT Card",
        short_name: "SBT Card",
        description: "Claim soulbound credential",
        url: "/build/card",
      },
      {
        name: "Dashboard",
        short_name: "My /me",
        description: "Your dashboard",
        url: "/me",
      },
    ],
  };
}
