import type { MetadataRoute } from "next";

/**
 * /sitemap.xml — auto-generated by Next.js App Router.
 *
 * Includes marketing pages (Wave 2E) + pillar landings (Waves 2B/2C/2D
 * may add more deep links by editing this file when their pages stabilize).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://web3.cuvetsmo.com";
  const now = new Date();

  return [
    { url: `${base}/`, lastModified: now, changeFrequency: "weekly", priority: 1 },
    { url: `${base}/about`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/glossary`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/learn/wallet-101`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/play/mint`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/build/card`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/lab/token-forge`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
  ];
}
