/**
 * Extract ABIs from Foundry build artifacts and emit lib/contracts.ts.
 *
 * Usage: node contracts/script/extract-abis.js
 *
 * Writes to ../../lib/contracts.ts (atomic, full rewrite).
 */

const fs = require("fs");
const path = require("path");

const CONTRACTS_ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(CONTRACTS_ROOT, "out");
const TARGET_FILE = path.resolve(CONTRACTS_ROOT, "..", "lib", "contracts.ts");

const NAMES = [
  "OrgRegistry",
  "VetSBTCard",
  "BadgeRegistry",
  "FirstStepsSBT",
  "Guestbook",
  "TokenImplementation",
  "TokenFactory",
  "NFTImplementation",
  "NFTFactory",
  "SBTFactory",
  "GovernorFactory",
];

function readAbi(name) {
  const p = path.join(OUT_DIR, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(p)) throw new Error(`Missing artifact: ${p}`);
  const j = JSON.parse(fs.readFileSync(p, "utf8"));
  return j.abi;
}

// Hand-rolled mapping so we get the names other Wave 2 agents expect.
const CONST_NAMES = {
  OrgRegistry: "ORG_REGISTRY",
  VetSBTCard: "VET_SBT_CARD",
  BadgeRegistry: "BADGE_REGISTRY",
  FirstStepsSBT: "FIRST_STEPS_SBT",
  Guestbook: "GUESTBOOK",
  TokenImplementation: "TOKEN_IMPL",
  TokenFactory: "TOKEN_FACTORY",
  NFTImplementation: "NFT_IMPL",
  NFTFactory: "NFT_FACTORY",
  SBTFactory: "SBT_FACTORY",
  GovernorFactory: "GOVERNOR_FACTORY",
};

function toConst(name) {
  if (!CONST_NAMES[name]) throw new Error(`No CONST_NAME mapping for ${name}`);
  return CONST_NAMES[name];
}

function envName(name) {
  return `NEXT_PUBLIC_${toConst(name)}_ADDRESS`;
}

const abis = Object.fromEntries(NAMES.map((n) => [n, readAbi(n)]));

const header = `/**
 * Contract addresses + ABIs for web3.cuvetsmo.com
 *
 * GENERATED by contracts/script/extract-abis.js — do not edit by hand.
 * Re-run after redeploying contracts:
 *   cd contracts && forge build && node script/extract-abis.js
 *
 * Addresses are read from NEXT_PUBLIC_* env vars so we can rotate across
 * testnet redeploys without touching code.
 */

import type { Address } from "viem";

const z = "0x0000000000000000000000000000000000000000" as Address;

const asAddress = (v: string | undefined): Address =>
  v && v.startsWith("0x") && v.length === 42 ? (v as Address) : z;

export const CONTRACTS = {
  // Core registries — Build pillar
  ORG_REGISTRY: asAddress(process.env.NEXT_PUBLIC_ORG_REGISTRY_ADDRESS),
  VET_SBT_CARD: asAddress(process.env.NEXT_PUBLIC_VET_SBT_CARD_ADDRESS),
  BADGE_REGISTRY: asAddress(process.env.NEXT_PUBLIC_BADGE_REGISTRY_ADDRESS),
  FIRST_STEPS_SBT: asAddress(process.env.NEXT_PUBLIC_FIRST_STEPS_SBT_ADDRESS),
  GUESTBOOK: asAddress(process.env.NEXT_PUBLIC_GUESTBOOK_ADDRESS),

  // The Lab factories + implementations
  TOKEN_IMPL: asAddress(process.env.NEXT_PUBLIC_TOKEN_IMPL_ADDRESS),
  TOKEN_FACTORY: asAddress(process.env.NEXT_PUBLIC_TOKEN_FACTORY_ADDRESS),
  NFT_IMPL: asAddress(process.env.NEXT_PUBLIC_NFT_IMPL_ADDRESS),
  NFT_FACTORY: asAddress(process.env.NEXT_PUBLIC_NFT_FACTORY_ADDRESS),
  SBT_FACTORY: asAddress(process.env.NEXT_PUBLIC_SBT_FACTORY_ADDRESS),
  GOVERNOR_FACTORY: asAddress(process.env.NEXT_PUBLIC_GOVERNOR_FACTORY_ADDRESS),
} as const;

/**
 * Returns true when every contract address has been wired.
 */
export function contractsReady(): boolean {
  return Object.values(CONTRACTS).every((addr) => addr !== z);
}

/** Per-contract readiness check. */
export function isReady(addr: Address): boolean {
  return addr !== z;
}

/**
 * Multi-chain deployment record. Filled in by Wave 2A deploy script.
 * Read directly when you need to switch the wagmi config or render
 * an "explorer link" — but day-to-day, prefer CONTRACTS above which
 * picks up the active-chain address from env.
 */
export const DEPLOYED = {
  baseSepolia: {
    chainId: 84532,
    orgRegistry: "" as Address | "",
    vetSbtCard: "" as Address | "",
    badgeRegistry: "" as Address | "",
    firstStepsSbt: "" as Address | "",
    guestbook: "" as Address | "",
    tokenImpl: "" as Address | "",
    tokenFactory: "" as Address | "",
    nftImpl: "" as Address | "",
    nftFactory: "" as Address | "",
    sbtFactory: "" as Address | "",
    governorFactory: "" as Address | "",
  },
  base: {
    chainId: 8453,
    orgRegistry: "" as Address | "",
    vetSbtCard: "" as Address | "",
    badgeRegistry: "" as Address | "",
    firstStepsSbt: "" as Address | "",
    guestbook: "" as Address | "",
  },
} as const;

`;

const sections = NAMES.map((n) => {
  const constName = `${toConst(n)}_ABI`;
  return `export const ${constName} = ${JSON.stringify(abis[n], null, 2)} as const;`;
}).join("\n\n");

const footer = `\n`;

fs.writeFileSync(TARGET_FILE, header + sections + footer, "utf8");
console.log(`Wrote ${TARGET_FILE}`);
console.log(`Contracts: ${NAMES.length}`);
console.log(`Total bytes: ${(header + sections + footer).length}`);
